// @ts-check
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const boundaries = require('eslint-plugin-boundaries');
const tsPlugin = require('@typescript-eslint/eslint-plugin');

/**
 * The conventions in CLAUDE.md, enforced by a tool instead of by memory.
 *
 * Every rule here exists because breaking it has already cost something, or
 * would cost something silently. Where a rule encodes a convention its number
 * is named, so a failure points at the reasoning rather than just a line.
 *
 * A few rules are deliberately OFF. Each says why, because "we turned it off"
 * with no reason is how a lint config rots — the next person cannot tell a
 * considered exception from an unexamined one.
 */

module.exports = defineConfig([
  expoConfig,

  {
    ignores: [
      'node_modules/**',
      'android/**',
      '.expo/**',
      'dist/**',
      'db/migrations/**', // generated by drizzle-kit; never hand-edited
      'global.css', // generated by npm run theme:css
      'pcref/**', // the web app: design and domain reference only
    ],
  },

  // ---------------------------------------------------------------------
  // Architecture: the import direction that keeps features independent
  // ---------------------------------------------------------------------
  {
    plugins: { boundaries },
    settings: {
      'boundaries/include': ['app/**', 'features/**', 'data/**', 'components/**', 'db/**', 'lib/**'],
      // ORDER MATTERS: the first pattern that matches wins. `feature` comes
      // before `components` because features/groups/components/* is a
      // FEATURE's own UI, not the shared components/ layer.
      'boundaries/elements': [
        { type: 'app', pattern: 'app/**', partialMatch: false },
        // capture: the feature's own name, so a feature can be told from a sibling.
        { type: 'feature', pattern: 'features/*/**', partialMatch: false, capture: ['name'] },
        { type: 'data', pattern: 'data/**', partialMatch: false },
        { type: 'components', pattern: 'components/**', partialMatch: false },
        { type: 'db', pattern: 'db/**', partialMatch: false },
        { type: 'lib', pattern: 'lib/**', partialMatch: false },
      ],
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          message:
            'This import crosses a layer boundary (CLAUDE.md #9). Allowed: app → features → (components | data) → db → lib, and a feature may never import a sibling — move the shared thing DOWN into data/, components/ or lib/.',
          policies: [
            {
              from: [{ element: { type: 'app' } }],
              allow: [
                { to: { element: { type: 'feature' } } },
                { to: { element: { type: 'components' } } },
                { to: { element: { type: 'data' } } },
                { to: { element: { type: 'lib' } } },
              ],
            },
            {
              // A feature may import its OWN files, never a sibling. Anything
              // two features need moves down into data/, components/ or lib/.
              from: [{ element: { type: 'feature' } }],
              allow: [
                { to: { element: { type: 'feature', captured: { name: '{{from.captured.name}}' } } } },
                { to: { element: { type: 'data' } } },
                { to: { element: { type: 'components' } } },
                { to: { element: { type: 'db' } } },
                { to: { element: { type: 'lib' } } },
              ],
            },
            {
              from: [{ element: { type: 'data' } }],
              allow: [
                { to: { element: { type: 'data' } } },
                { to: { element: { type: 'db' } } },
                { to: { element: { type: 'lib' } } },
              ],
            },
            {
              from: [{ element: { type: 'components' } }],
              allow: [{ to: { element: { type: 'components' } } }, { to: { element: { type: 'lib' } } }],
            },
            {
              from: [{ element: { type: 'db' } }],
              allow: [{ to: { element: { type: 'db' } } }, { to: { element: { type: 'lib' } } }],
            },
            { from: [{ element: { type: 'lib' } }], allow: [{ to: { element: { type: 'lib' } } }] },
          ],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------
  // The conventions, as rules
  // ---------------------------------------------------------------------
  {
    files: ['**/*.{ts,tsx,js,jsx}'],
    // eslint-config-expo registers this plugin only inside its own objects.
    plugins: { '@typescript-eslint': tsPlugin },
    rules: {
      // #1 — No network. Ever. The release build does not declare INTERNET.
      'no-restricted-globals': [
        'error',
        { name: 'fetch', message: 'This app makes no network requests (CLAUDE.md #1).' },
        { name: 'XMLHttpRequest', message: 'This app makes no network requests (CLAUDE.md #1).' },
        { name: 'WebSocket', message: 'This app makes no network requests (CLAUDE.md #1).' },
        { name: 'EventSource', message: 'This app makes no network requests (CLAUDE.md #1).' },
      ],

      'no-restricted-syntax': [
        'error',
        // #2 — money is integer paise; text becomes paise only in lib/money.ts.
        {
          selector: "CallExpression[callee.name='parseFloat']",
          message: 'Only lib/money.ts may parse a float. Use parseAmountToPaise (CLAUDE.md #2).',
        },
        {
          selector: "CallExpression[callee.property.name='toLocaleString']",
          message: 'toLocaleString falls back to US grouping without ICU. Use formatINR / formatCount (CLAUDE.md #2).',
        },
        // #8 — writeTx callbacks are SYNCHRONOUS. Drizzle's expo driver commits
        // when the callback RETURNS, and an async one returns at its first
        // await, so everything after that runs outside the transaction. The
        // dev seeder shipped this bug once; db/tx.ts now throws on it at
        // runtime, and this catches it before the code is ever run.
        {
          selector: 'CallExpression[callee.name=/^(writeTx|runWriteTx)$/] > ArrowFunctionExpression[async=true]',
          message: 'A writeTx callback must be synchronous: the driver commits when it returns (CLAUDE.md #8).',
        },
        {
          selector: 'CallExpression[callee.name=/^(writeTx|runWriteTx)$/] > FunctionExpression[async=true]',
          message: 'A writeTx callback must be synchronous: the driver commits when it returns (CLAUDE.md #8).',
        },
        {
          selector: "CallExpression[callee.property.name='transaction'] > ArrowFunctionExpression[async=true]",
          message: 'A transaction callback must be synchronous (CLAUDE.md #8). Use writeTx.',
        },
        {
          selector: "CallExpression[callee.property.name='transaction'] > FunctionExpression[async=true]",
          message: 'A transaction callback must be synchronous (CLAUDE.md #8). Use writeTx.',
        },
      ],

      // #6 — reads go through useDbQuery over readDb, never Drizzle's own
      // hook: it re-runs once per changed row, misses joined tables, races,
      // and swallows errors (the 2026-09-14 decision).
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'drizzle-orm/expo-sqlite',
              importNames: ['useLiveQuery'],
              message: 'Use useDbQuery over readDb (CLAUDE.md #6).',
            },
          ],
          // R2-5: anything outside your own folder is imported by @/ path.
          // `../../lib/theme` breaks every time a file moves; `@/lib/theme`
          // never does. Relative imports stay for siblings in the same unit.
          patterns: [
            {
              group: ['../../*'],
              message: 'Import across folders with the @/ alias (e.g. @/lib/money), not ../../',
            },
            {
              // Seeding 50k rows and timing queries is dev-only (CLAUDE.md #17).
              group: ['@/db/dev/*'],
              message: 'db/dev is for the dev harness and benchmarks only; production code never imports it.',
            },
          ],
        },
      ],

      // Caught B9: a hook read `colors` without listing it, so month headers
      // kept the old palette after a theme switch.
      'react-hooks/exhaustive-deps': 'error',

      // 24 files imported `colors` and then shadowed it with useColors().
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],

      /**
       * OFF, deliberately — three React Compiler rules that cannot model how
       * this app is built:
       *
       * `immutability` flags writes to Reanimated shared values
       * (`x.value = …`) inside worklets. That is not React state; the
       * assignment IS the API, and it runs on the UI thread, which is why the
       * charts and the tab bar stay smooth.
       *
       * `refs` flags the ref-mirror pattern used to give a callback a stable
       * identity while still seeing the latest props (`olderRef.current =
       * older`). It is load-bearing: without it `useTransactionPages` would
       * rebuild its callbacks every render and FlashList would remount cells.
       *
       * `set-state-in-effect` flags values deliberately re-derived when their
       * input changes — the ledger clearing a selection when the filter
       * changes, AnimatedAmount jumping to its final value when motion is off.
       *
       * All three would be permanent noise, and noise is how a lint run stops
       * being read. Revisit if this project adopts the React Compiler.
       */
      'react-hooks/immutability': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',

      /**
       * OFF: the apostrophes this flags are typographic (U+2019) inside
       * user-facing copy — "let's", "that's". They are correct as written, and
       * escaping them would make the sentences harder to read in the source.
       */
      'react/no-unescaped-entities': 'off',

      /**
       * OFF: `incompatible-library` fires on react-hook-form's `watch()`,
       * which the React Compiler cannot analyse. The forms are correct and
       * tested; there is nothing to act on.
       */
      'react-hooks/incompatible-library': 'off',

      /**
       * OFF: `no-duplicates` counts a value import and a `import type` from
       * the same module as duplicates. Keeping types on their own line is
       * deliberate here — it is what makes it obvious that `db/schema` is
       * imported for its TYPES in pure logic that must not pull the runtime in.
       */
      'import/no-duplicates': 'off',
    },
  },

  // The dev harness and the per-feature benchmark lists are the only callers
  // of db/dev. Same rules as everywhere else, minus that one pattern.
  {
    files: ['app/dev.tsx', 'features/*/benchmark.ts', 'db/dev/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'drizzle-orm/expo-sqlite',
              importNames: ['useLiveQuery'],
              message: 'Use useDbQuery over readDb (CLAUDE.md #6).',
            },
          ],
          patterns: [{ group: ['../../*'], message: 'Import across folders with the @/ alias, not ../../' }],
        },
      ],
    },
  },

  /**
   * lib/ holds pure logic that Node tests load directly, so it must stay free
   * of React Native. The listed files are the deliberate exceptions: lib/db is
   * the read runtime, and the rest are theme/motion glue a component uses.
   */
  {
    files: ['lib/**/*.ts'],
    ignores: ['lib/db/**', 'lib/theme.ts', 'lib/themeStore.ts', 'lib/today.ts', 'lib/motion.ts', 'lib/icons.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: 'react-native', message: 'Keep lib/ loadable in Node: pure logic must not import React Native.' },
            { name: 'react', message: 'Keep lib/ loadable in Node: pure logic must not import React.' },
          ],
        },
      ],
    },
  },

  /**
   * The three routes that still reach into db/ (review A7).
   *
   * `app/_layout.tsx` is legitimate and permanent: something has to boot the
   * database, and the root layout is where that belongs (CLAUDE.md #9, rule 3).
   *
   * `app/dev.tsx` and `app/settings/index.tsx` are DEBT. R4-4 moves both into
   * features/, and then this list shrinks to _layout alone. Named here rather
   * than disabled inline so the debt is countable: when one entry remains,
   * that part of R4 is done.
   */
  {
    files: ['app/_layout.tsx', 'app/dev.tsx', 'app/settings/index.tsx'],
    rules: { 'boundaries/dependencies': 'off' },
  },

  // Components are presentational: they receive data, they never fetch it.
  {
    files: ['components/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/db/client', '**/db/read', '@/db/client', '@/db/read'],
              message: 'Components take data as props. SQL lives in a data layer (CLAUDE.md #4).',
            },
          ],
        },
      ],
    },
  },

  // lib/money.ts is the one file allowed to parse and format money.
  {
    files: ['lib/money.ts'],
    rules: { 'no-restricted-syntax': 'off' },
  },

  // Tests may reach anywhere: their job is to run the shipped code against a
  // database the app never uses (CLAUDE.md #18).
  {
    files: ['**/__tests__/**/*.{ts,tsx}', '**/*.test.{ts,tsx}'],
    rules: {
      'boundaries/dependencies': 'off',
      'no-restricted-imports': 'off',
      'no-restricted-syntax': 'off',
    },
  },

  /**
   * The lint fixtures break rules ON PURPOSE (npm run lint:selftest).
   *
   * They are not in `ignores`, because a config-level ignore cannot be undone
   * by --no-ignore, which would make them unlintable and the self-test
   * useless. Instead the everyday `npm run lint` skips the folder via its own
   * --ignore-pattern, and the self-test lints them directly.
   */

  // Build and tooling scripts run in Node, not in the app: CommonJS, and the
  // Node globals (__dirname, process, require) that the app's config forbids.
  {
    files: ['scripts/**/*.{ts,js}', 'plugins/**/*.js', '*.config.{js,ts}', 'eslint.config.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'writable',
        require: 'readonly',
        process: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      'boundaries/dependencies': 'off',
      'no-restricted-imports': 'off',
      'no-restricted-syntax': 'off',
      'no-restricted-globals': 'off',
    },
  },
]);
