const fs = require('fs');
const path = require('path');
const { withAndroidManifest, withDangerousMod } = require('expo/config-plugins');

/**
 * Android auto-backup rules (Layer 2 of the durability plan, CLAUDE.md → Backup & Restore).
 *
 * EXCLUDE-ONLY on purpose: the moment a rules file contains an <include>,
 * Android backs up ONLY the included paths, and the database would silently
 * stop being backed up. Everything is backed up except:
 *
 *   file  SQLite/spendwise.db-wal   the WAL is checkpointed into the main file when
 *   file  SQLite/spendwise.db-shm   the app backgrounds; copying these separately can
 *                                   produce a torn database
 *   file  SQLite/spendwise.db.converting        in-progress legacy conversion
 *   file  snapshots/                pre-migration copies (large, device-local safety net)
 *   file  legacy/                   encrypted originals kept for one launch after conversion
 *   file  unreadable/               databases moved aside by "Start fresh"
 *   sharedpref SecureStore.xml      Keystore-wrapped values cannot be decrypted on another
 *                                   device; restoring them only produces DecryptException
 *
 * Keep in step with db/files.ts. Sheet templates (files/sheets/, Phase 6A) are
 * backed up by default because nothing excludes them.
 */

const EXCLUDES = [
  ['file', 'SQLite/spendwise.db-wal'],
  ['file', 'SQLite/spendwise.db-shm'],
  ['file', 'SQLite/spendwise.db.converting'],
  ['file', 'snapshots/'],
  ['file', 'legacy/'],
  ['file', 'unreadable/'],
  ['sharedpref', 'SecureStore.xml'],
];

const BACKUP_RULES = 'spendwise_backup_rules';
const EXTRACTION_RULES = 'spendwise_data_extraction_rules';

function excludeLines(indent) {
  return EXCLUDES.map(([domain, p]) => `${indent}<exclude domain="${domain}" path="${p}"/>`).join('\n');
}

/** Android 11 and lower. */
function fullBackupContentXml() {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js. Exclude-only: any include rule would narrow the backup to just what it names. -->
<full-backup-content>
${excludeLines('  ')}
</full-backup-content>
`;
}

/** Android 12 and higher: cloud backup and device-to-device transfer. */
function dataExtractionRulesXml() {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js. Exclude-only: any include rule would narrow the backup to just what it names. -->
<data-extraction-rules>
  <cloud-backup>
${excludeLines('    ')}
  </cloud-backup>
  <device-transfer>
${excludeLines('    ')}
  </device-transfer>
</data-extraction-rules>
`;
}

function withBackupRules(config) {
  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${BACKUP_RULES}.xml`), fullBackupContentXml());
      fs.writeFileSync(path.join(dir, `${EXTRACTION_RULES}.xml`), dataExtractionRulesXml());
      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) throw new Error('withBackupRules: AndroidManifest has no <application>');
    app.$['android:fullBackupContent'] = `@xml/${BACKUP_RULES}`;
    app.$['android:dataExtractionRules'] = `@xml/${EXTRACTION_RULES}`;
    return cfg;
  });
}

module.exports = withBackupRules;
module.exports.EXCLUDES = EXCLUDES;
module.exports.fullBackupContentXml = fullBackupContentXml;
module.exports.dataExtractionRulesXml = dataExtractionRulesXml;
