import {
  type LucideIcon,
  Baby,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Car,
  CircleEllipsis,
  CirclePlus,
  Clapperboard,
  Coffee,
  Coins,
  CreditCard,
  Droplets,
  Dumbbell,
  Film,
  Fish,
  Flower2,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Hotel,
  House,
  Landmark,
  Laptop,
  Music,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Tag,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react-native';

/**
 * Icon NAME → lucide component.
 *
 * Split out of CategoryIcon so the set of names can be checked without
 * rendering anything: `lib/__tests__/icons.test.ts` asserts these keys are
 * exactly `ICON_NAMES`. `lib/icons.ts` claimed such a test existed for months
 * while none did (review T4), and the cost of that gap is invisible — a name
 * in one list but not the other renders a silent fallback tag, so a category
 * quietly loses its icon and nothing fails.
 *
 * This file only touches lucide's exports, never React Native's runtime, so
 * Node can import it.
 */
export const ICON_COMPONENTS: Record<string, LucideIcon> = {
  // The seeded set — matches the web app's category icons.
  utensils: Utensils,
  'shopping-basket': ShoppingBasket,
  car: Car,
  'shopping-bag': ShoppingBag,
  clapperboard: Clapperboard,
  receipt: Receipt,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  house: House,
  plane: Plane,
  repeat: Repeat,
  sparkles: Sparkles,
  gift: Gift,
  'trending-up': TrendingUp,
  wallet: Wallet,
  'circle-plus': CirclePlus,
  'circle-ellipsis': CircleEllipsis,
  // Extra choices for categories the user creates.
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  cake: Cake,
  fuel: Fuel,
  bus: Bus,
  'train-front': TrainFront,
  bike: Bike,
  smartphone: Smartphone,
  laptop: Laptop,
  tv: Tv,
  wifi: Wifi,
  zap: Zap,
  droplets: Droplets,
  shirt: Shirt,
  scissors: Scissors,
  dumbbell: Dumbbell,
  pill: Pill,
  baby: Baby,
  'paw-print': PawPrint,
  fish: Fish,
  'flower-2': Flower2,
  music: Music,
  film: Film,
  'gamepad-2': Gamepad2,
  ticket: Ticket,
  hotel: Hotel,
  'book-open': BookOpen,
  briefcase: Briefcase,
  'building-2': Building2,
  landmark: Landmark,
  'piggy-bank': PiggyBank,
  coins: Coins,
  'hand-coins': HandCoins,
  'credit-card': CreditCard,
  wrench: Wrench,
  tag: Tag,
};

/** Shown when a stored name matches nothing — a renamed lucide icon, say. */
export const FALLBACK_ICON: LucideIcon = Tag;
